name: Build firmware for RAX3000M

on:
  push:
    paths:
      - 'RAX3000M/*'
      - '.github/workflows/rax3000m.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: write
    with:
      repo: https://github.com/hanwckf/immortalwrt-mt798x
      branch: openwrt-21.02
      config: RAX3000M/my3.config
