name: Build firmware for RAX3000M

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: write
    with:
      repo: https://github.com/hanwckf/immortalwrt-mt798x
      branch: openwrt-21.02
      config: RAX3000M/.config
