name: Build firmware for Redmi AC2100

on:
  push:
    paths:
      - 'RM2100/*'
      - '.github/workflows/rm2100.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: write
    with:
      repo: https://github.com/immortalwrt/immortalwrt
      branch: openwrt-24.10
      config: RM2100/immortalwrt.config
